---
name: cmpsc-203-spring-2021-practical5
break: true
indent: 4
---

# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
termfrequency:
        compute_tf_pipeline.py:
            ConfirmFileExists
            CountMultipleLineComments --language Python --count 7
            CountSingleLineComments --language Python --count 6
            MatchFileFragment --fragment "TODO" --count 0 --exact
            MatchFileFragment --fragment "with open" --count 1
            MatchFileFragment --fragment "for w in word_list" --count 1

tests:
        test_compute_tf_pipeline.py:
            ConfirmFileExists
            CountMultipleLineComments --language Python --count 5
            CountSingleLineComments --language Python --count 0
            MatchFileFragment --fragment "test_" --count 5
            MatchFileFragment --fragment "assert" --count 5
            MatchFileFragment --fragment "@pytest.mark.parametrize" --count 2
            MatchFileFragment --fragment "TODO" --count 0 --exact
tests:
        conftest.py:
            ConfirmFileExists
            MatchFileFragment --fragment "TODO" --count 0 --exact

tests:
        __init__.py:
            ConfirmFileExists
            MatchFileFragment --fragment "TODO" --count 0 --exact
scripts:
        cover.sh:
            ConfirmFileExists
            MatchFileFragment --fragment "TODO" --count 0 --exact

scripts:
        lint.sh:
            ConfirmFileExists
            MatchFileFragment --fragment "TODO" --count 0 --exact

scripts:
        test.sh:
            ConfirmFileExists
            MatchFileFragment --fragment "TODO" --count 0 --exact

# --> check the technical writing
writing/reflection.md:
    ConfirmFileExists
    CountFileWords --count 400
    CountMarkdownTags --tag "heading" --count 9 --exact
    CountMarkdownTags --tag "code_block" --count 1 --exact
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "![" --count 1

# --> check the number of commits beyond a threshold
CountCommits --count 5
